### ISSUE TITLE
Persistent non-blocking dialog design

### ISSUE THREAD

**Issue by matthewma7** [OpenGeoscience/resonantgeoview#1]
In this application or application depend on this.
There is a need for persist non-blocking dialog, [dialog](https://vuetifyjs.com/en/components/dialogs#introduction) provided by Vuetify are all blocking and non-persistent. 
One use case is for the info popup of the map. Where user would need to close and open the dialog mutiple times to see info popup of another point on map.
![chrome_2018-09-20_13-03-19](https://user-images.githubusercontent.com/3123478/45835380-f3425000-bcd7-11e8-8c44-62cc31497443.png)
So, there is a need to have design for a persistent non-blocking dialog.

**Comment by matthewma7** [comment]
Assigning to @jtomeck

**Comment by jtomeck** [comment]
@matthewma7 - The dialogue component has props for hiding the overlay and making it persistent. Is it possible to use those props and add positioning to achieve this? I can still do a design for this, but this knowledge may inform my decisions.

**Comment by matthewma7** [comment]
@jtomeck Oh, yes. I didn't notice those props, thanks for that. However, it seems the position and transition effect is not open to developers. If you like the s3 slide in effect, no design is needed, I'll find a way to implement a slide in with the dialog look. 
If you think another fashion and would like to create a design, please welcome to do so.

**Comment by jtomeck** [comment]
Let's see where this leads us, and once you have something we can meet and I can weigh in/make suggestions. Not straying far from the components Vuetify provides may help us avoid having to maintain too many custom components based on Vuetify's. Would you agree?

**Comment by matthewma7** [comment]
Hi @jtomeck, I looked into this. Using pure CSS won't achieve what we need, but found I can get what we need with a thin wrapper around Vuetify's dialog. 😃

**Comment by jtomeck** [comment]
@matthewma7 - Great! Would you mind posting a screenshot? I'm curious 👍

**Comment by matthewma7** [comment]
@jtomeck, Sure, this is what it looks like.

![2018-09-24_14-04-35](https://user-images.githubusercontent.com/3123478/45969962-40d5fa00-c003-11e8-9dd7-0c05019e2b7f.gif)


I just got this working, let me know if would like to see the code. I might need to do some cleaning up.

**Comment by matthewma7** [comment]
Resolved by https://github.com/OpenGeoscience/resonantgeoview/commit/1553197723efb6760bbbca931386b143988672fb
with the implementation from above
