### ISSUE TITLE
Add support for VTK.js view 

### ISSUE THREAD

**Issue by aashish24** [OpenGeoscience/resonantgeoview#3]

**Comment by matthewma7** [comment]
resolved by https://github.com/OpenGeoscience/resonantgeoview/commit/f1867a4b80b7fcb422d819f8963a43071d87d30e
with initial OBJ support. It requires the OBJ file has 4 comment rows to define it's position like this
```
#x offset: 749375.520858
#y offset: 4407077.637
#z offset: 239.389936
#srs: +units=m +proj=utm +zone=16 +ellps=WGS84
```
